/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alasUCU;

import codigoGrafos.TArista;
import codigoGrafos.TCamino;
import codigoGrafos.TCaminos;
import codigoGrafos.TGrafoDirigido;
import codigoGrafos.TVertice;
import java.text.ParseException;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juanma
 */
public class FramePrincipal extends javax.swing.JFrame {

    TGrafoDirigido gd;
    LinkedList<TVertice> vertices;
    LinkedList<TArista> aristas;

    /**
     * Genera el jFrame Principal de la aplicacion.
     * Se carga la informacion necesaria
     */
    public FramePrincipal() {
        initComponents();
        vertices = ClaseAuxiliar.cargarAeropuertos("src/alasUCU/aeropuertos.csv");
        try {
            aristas = ClaseAuxiliar.cargarVuelos("src/alasUCU/vuelos.csv");
        } catch (ParseException exc) {
            exc.printStackTrace();
        }
        gd = ClaseAuxiliar.cargarGrafo(vertices, aristas, TGrafoDirigido.class);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabelFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaPrincipal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        labelVuelosDisponibles = new javax.swing.JLabel();
        jLabelVueloMasBarato = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVueloMasBarato = new javax.swing.JTextArea();
        jLabelVueloMasCorto = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVueloMasCorto = new javax.swing.JTextArea();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelOrigen.setText("Origen");

        jLabelDestino.setText("Destino");

        jLabelFecha.setText("Fecha");

        JTextAreaPrincipal.setColumns(20);
        JTextAreaPrincipal.setRows(5);
        jScrollPane1.setViewportView(JTextAreaPrincipal);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("ALAS UCU");

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        labelVuelosDisponibles.setText("Vuelos disponibles para la fecha seleccionada:");

        jLabelVueloMasBarato.setText("Vuelo mas barato disponible:");

        jTextAreaVueloMasBarato.setColumns(20);
        jTextAreaVueloMasBarato.setRows(5);
        jScrollPane2.setViewportView(jTextAreaVueloMasBarato);

        jLabelVueloMasCorto.setText("Vuelo más corto:");

        jTextAreaVueloMasCorto.setColumns(20);
        jTextAreaVueloMasCorto.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVueloMasCorto);

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelOrigen)
                        .addGap(41, 41, 41)
                        .addComponent(jLabelDestino))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelVueloMasCorto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVuelosDisponibles)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabelVueloMasBarato)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrigen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFecha)
                                .addComponent(jLabelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(jButtonActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVuelosDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelVueloMasBarato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVueloMasCorto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodos a realizarse una vez que el boton fue apretado
     * @param evt 
     */
    
    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        String origen = jComboBoxOrigen.getSelectedItem().toString();
        String destino = jComboBoxDestino.getSelectedItem().toString();
        Date fecha = jDateChooserFecha.getDate();
        if (origen != null && destino != null && fecha != null) {
            try {
                JTextAreaPrincipal.setText("");
                jTextAreaVueloMasBarato.setText("");
                jTextAreaVueloMasCorto.setText("");
                TCaminos cam = gd.todosLosCaminos(origen, destino, fecha);
                TCamino camBarato = cam.caminoMasBarato();
                TCamino camRapido = cam.menosTiempoDeVuelo();
                for (TCamino camino : cam.getCaminos()) {
                    TVertice o = gd.buscarVertice(camino.getOrigen().getEtiqueta());
                    TVertice d = gd.buscarVertice(camino.getUltimaEtiqueta());
                    JTextAreaPrincipal.append("ORIGEN: " + o.getDatos().getNombre_Aero() + " (" + origen + ")" + "\n");
                    JTextAreaPrincipal.append("DESTINO: " + d.getDatos().getNombre_Aero() + " (" + destino + ")" + "\n");
                    JTextAreaPrincipal.append("CAMINO COMPLETO: " + camino.imprimirEtiquetas() + "\n");
                    JTextAreaPrincipal.append("COSTO: " + camino.getCostoTotal() + "\n");
                    JTextAreaPrincipal.append("--------" + "\n");
                }
                jTextAreaVueloMasBarato.append(camBarato.imprimirEtiquetas() + " COSTO -> " + camBarato.getCostoTotal());
                jTextAreaVueloMasCorto.append(camRapido.imprimirEtiquetas() + " TIEMPO -> " + camRapido.getTiempoTotalVuelo());
            }
            catch (NullPointerException exc) {
                JOptionPane.showMessageDialog(null, "No hay conexiones entre los aeropuertos para ese dia");
            }
        }

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);

            }
        });
    }

    /**
     * Encargado de subir la informacion correspondiente a los 
     * jComboBox del frame 
     */
    
    public void cargarDatos() {
        jComboBoxOrigen.removeAllItems();
        jComboBoxDestino.removeAllItems();
        for (TVertice v : vertices) {
            if (!v.getEtiqueta().equals("")) {
                jComboBoxOrigen.addItem((String) v.getEtiqueta());
                jComboBoxDestino.addItem((String) v.getEtiqueta());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTextAreaPrincipal;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelVueloMasBarato;
    private javax.swing.JLabel jLabelVueloMasCorto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaVueloMasBarato;
    private javax.swing.JTextArea jTextAreaVueloMasCorto;
    private javax.swing.JLabel labelVuelosDisponibles;
    // End of variables declaration//GEN-END:variables
}
